# theme: jekyll-theme-minimal
title: Italian Software Engineer and Entrepreneur
name: Stefano Zeppieri
description: Software Engineer and Ph.D. Student at Sapienza University of Rome. Researching Large Language Models and Human-Computer Interaction. Passionate about creating intuitive, AI-driven web experiences.
google_analytics: G-H280YB34L0
url: "https://stefanozeppieri.com"
logo: /profile.jpg
socials:
  linkedin: https://www.linkedin.com/in/stefano-zeppieri/
  instagram: https://instagram.com/stepzepp
  twitter: https://twitter.com/stepzepp
  facebook: https://www.facebook.com/stepzepp
  email: me@stefanozeppieri.com
image:
  path: /profile.jpg
  height: 1365
  width: 2048
author: Stefano Zeppieri
social:
  name: Stefano Zeppieri
  links:
    - https://www.linkedin.com/in/stefano-zeppieri/
    - https://instagram.com/stepzepp
    - https://twitter.com/stepzepp
    - https://www.facebook.com/stepzepp
  type: Person
webmaster_verifications:
  google: HGi1DCB_cq4iW3oNa_xeKYgQ770SwE3ZzQcgh8Ske3I